# Generated by Django 5.0.4 on 2025-06-22 08:09

import django.core.validators
import organizers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='*Allowed names contain letters, digits, spaces, and hyphens.', max_length=110, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='The company name is invalid!', regex='^[A-Za-z0-9\\- ]+$')])),
                ('phone_number', models.CharField(error_messages={'unique': 'That phone number is already in use!'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain digits only.', regex='^\\d+$')])),
                ('secret_key', models.CharField(help_text='*Pick a combination of 4 unique digits.', max_length=4, validators=[organizers.validators.validate_secret_key])),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
